# Generated by Django 3.2.23 on 2023-11-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('is_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemComprado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('preco', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('unidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompradoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('item_comprado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='itemComprado', to='maingigapizza.itemcomprado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField()),
                ('ingredientes', models.ManyToManyField(through='maingigapizza.ItemCompradoVenda', to='maingigapizza.ItemComprado')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoria_principal', to='maingigapizza.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_venda', to='maingigapizza.itemvenda')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pizza', to='maingigapizza.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subcategoria', to='maingigapizza.subcategoria'),
        ),
        migrations.AddField(
            model_name='itemcompradovenda',
            name='item_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='itemVenda', to='maingigapizza.itemvenda'),
        ),
    ]
