# Generated by Django 4.2.7 on 2023-11-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0003_alter_categoria_nome_alter_insumo_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompradoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_venda', to='maingigapizza.itemvenda')),
            ],
        ),
        migrations.RemoveField(
            model_name='iteminsumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='iteminsumo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sabor1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sabor2',
        ),
        migrations.RenameModel(
            old_name='Insumo',
            new_name='ItemComprado',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemInsumo',
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pizza', to='maingigapizza.pizza'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='ingredientes',
            field=models.ManyToManyField(through='maingigapizza.ItemCompradoVenda', to='maingigapizza.itemcomprado'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subcategoria', to='maingigapizza.subcategoria'),
        ),
        migrations.AddField(
            model_name='itemcompradovenda',
            name='item_comprado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='itemComprado', to='maingigapizza.itemcomprado'),
        ),
        migrations.AddField(
            model_name='itemcompradovenda',
            name='item_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='itemVenda', to='maingigapizza.itemvenda'),
        ),
    ]
