# Generated by Django 4.2.7 on 2023-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0004_itemcompradovenda_itemvenda_saborpizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomprado',
            name='unidade',
            field=models.CharField(default='und', max_length=255),
            preserve_default=False,
        ),
    ]
