# Generated by Django 4.2.7 on 2023-11-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoria_principal', to='maingigapizza.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField()),
                ('sabor1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pizzas_sabores_1', to='maingigapizza.item')),
                ('sabor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pizzas_sabores_2', to='maingigapizza.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_insumos', to='maingigapizza.insumo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_insumos', to='maingigapizza.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='ingredientes',
            field=models.ManyToManyField(through='maingigapizza.ItemInsumo', to='maingigapizza.insumo'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subcategoria', to='maingigapizza.subcategoria'),
        ),
    ]
