# Generated by Django 4.2.7 on 2023-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='preco',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
