# Generated by Django 3.2.23 on 2023-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0002_itemcomprado_is_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
