# Generated by Django 3.2.23 on 2023-12-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('ultima_interacao', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.usuario')),
            ],
        ),
    ]
