# Generated by Django 3.2.23 on 2023-12-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0005_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(default='cliente', max_length=64),
            preserve_default=False,
        ),
    ]
