# Generated by Django 3.2.23 on 2023-12-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0006_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
