# Generated by Django 3.2.23 on 2023-12-26 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0008_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaSolicitacao', models.DateTimeField(default=datetime.datetime(2023, 12, 26, 12, 10, 56, 892515))),
                ('horaEntrega', models.DateTimeField()),
                ('dataPedido', models.DateTimeField(default=datetime.datetime(2023, 12, 26, 12, 10, 56, 892515))),
                ('descricao', models.CharField(max_length=512)),
                ('isFinalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.itemvenda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.pedido')),
            ],
        ),
    ]
