# Generated by Django 3.2.23 on 2024-01-03 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0009_itempedido_pedido_pizzapedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='dataPedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='horaSolicitacao',
        ),
        migrations.AddField(
            model_name='pedido',
            name='datahoraSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 11, 17, 42, 703376)),
        ),
    ]
