# Generated by Django 3.2.23 on 2024-01-03 14:34

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maingigapizza", "0010_auto_20240103_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="id_usuario_pedido",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="usuario_pedido_id",
                to="maingigapizza.usuario",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedido",
            name="datahoraSolicitacao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 3, 11, 34, 8, 954872)
            ),
        ),
    ]
