# Generated by Django 3.2.23 on 2024-01-03 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0011_auto_20240103_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='datahoraSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 56, 16, 735464)),
        ),
        migrations.DeleteModel(
            name='PizzaPedido',
        ),
    ]
