# Generated by Django 3.2.23 on 2024-01-03 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0012_auto_20240103_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='datahoraSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 59, 11, 271590)),
        ),
        migrations.CreateModel(
            name='PizzaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.pizza')),
            ],
        ),
    ]
